Makefile, README.md, api/diagnostics.go, api/diagnostics_test.go, api/handlers.go, api/handlers_test.go, api/health.go, api/helpers.go, api/interfaces.go, api/pull.go, api/pull_test.go, api/router.go, api/structures.go, cmd/check.go, cmd/daemon.go, cmd/root.go, config/config.go, main.go, vendor/vendor.json
rename `3dt` to `dcos-diagnostics`
- replace all `3dt` occurrence in the code
- remove unused flags from `Makefile`
=> rename 3dt -> dcos-diagnostics

runner/runner.go, runner/runner_test.go
during the refactor the cluster check invocation was broken due to lack of unittests.
Fix the bug and add unittests to cover Cluster, Prestart and Poststart
=> fix cluster check invocation

cmd/check.go, runner/check.go, runner/check_test.go, runner/runner.go, runner/runner_test.go
This causes exec.FullOutput to respect the PATH env var when looking for the executable by setting the env when the runner process starts. The subprocess will then inherit the correct environment from the runner process.
=> Respect PATH env var when looking for check executables

api/diagnostics.go, api/diagnostics_test.go
[COPS-1875](https://jira.mesosphere.com/browse/COPS-1875)
having colons in diagnostics bundle name is a bad idea, this is a problem for windows environment.
this PR changes the naming convention for diagnostics bundle to
`bundle-$year-$month-$day-$unixtimestamp.zip`
=> change the diagnostics bundle name

api/diagnostics.go
all endpoints must return 200, otherwise it should be an error
=> update error report if requested endpoint returned unexpected response code

api/pull.go
if the dcos-diagnostics node responds with other then 200 status code,
we should make it clear in the logs.
=> make error message verbose

runner/check.go, runner/runner_test.go
[DCOS_OSS-2247](https://jira.mesosphere.com/browse/DCOS_OSS-2247)
there are several levels of errors when runner executes checks. The error
is considered to be an exception, where runner is unable to run the checks for
some reason. For example, when the check is not present in the path.
However if the command execution takes more time then defined in `timeout`
check property, it will be killed and also considered as an error. But in fact,
it should be a failed check. This PR fixes it.
=> runner: treat command timeout as a failed check

scripts/test.sh
This updates the test script to run tests and linting against the `config` and `cmd` packages in this project.
I verified the fix locally by adding unnecessary newlines to the end of `config/config.go` and running `make test` with and without this patch. `make test` reports the extra newlines and fails with this patch, and ignores them without it.
=> Run tests against the config and cmd packages

scripts/test.ps1
DC/OS Diagnostics tests for Windows are showing errors
` go get -u github.com/golang/lint `  fails to retrieve the golint package
updated the URL to point to the correct address
=> Update golint url

scripts/test.ps1
Issue: There is no error checking for function _unittest_with_coverage
Added a $LASTEXITCODE check
=> Add error checking for coverage unit tests

cmd/daemon.go, cmd/root.go
The description of `daemon` was copied from cobra example
and has noting to do with this project.
Long description for help has invalid command `check` which is not
implemented.
=> Fix command description

Dockerfile, api/diagnostics.go, api/diagnostics_test.go, api/handlers.go, api/handlers_test.go, api/helpers.go, api/helpers_linux.go, api/helpers_windows.go, api/pull.go, api/pull_test.go, api/router.go, api/structures.go, api/structures_test.go, scripts/test.sh
Currently primitive types are used for any domain objecst
in the system. This change intorduce Health type which is
aliased `int`. See: [PrimitiveObsession](http://wiki.c2.com/?PrimitiveObsession)
There is no need ot expose base route outside of the package.
This structure is implemented in different place.
There is no need to keep it.
=> Minor code improvements

.travis.yml, Gopkg.lock
> dep check is a read-only command that verifies dep's sync invariants
> are met. It's primarily intended for automated use (e.g. CI or git
> pre-commit hooks). We may expand it later to include more comprehensive
> checks. https://github.com/golang/dep/commit/3201ef6a3442d3167cd54fdae5b31b039caf08bf
=> Add `dep check` to CI

api/diagnostics.go, api/diagnostics_test.go
Try to find bundles locally before asking exhibitor. This is microoptimisation that is required by changes allowing any node to create its local bundle and serve it.
=> Search for bundles locally first

api/diagnostics.go
`path.Base` has a problem when the path contains drive. To fix this problem I switched to `filepath.Base` that return dir and filename.
See golang/go#7698
=> Use filepath.Base instead of path.Base

api/diagnostics.go, api/diagnostics_test.go, api/handlers.go
Current implementation silently goes over errors with reading `endpoint-config`. This commit changes this behaviour to fail when external config could not be loaded. No matter if the file is empty, does not exist or is invalid JSON.
Fixes: [DCOS_OSS-4130](https://jira.mesosphere.com/browse/DCOS_OSS-4130)
=> Fail when no external log providers config files

api/diagnostics.go, api/diagnostics_test.go, api/providers.go, api/testdata/endpoint-config.json
Current implementation iterate over slices to find the desired file. This commit replaces slices with maps to simplify this procedure. Providers were moved to separate file.
=> Replace slices with map

scripts/test.ps1
The following error occurs when running diagnostics tests:
*** Running 'golint' ... ***
package github.com/golang/lint/golint: code in directory D:\DCOS\diagnostics\src\github.com\golang\lint\golint expects import "golang.org/x/lint/golint"
Introduced with:
https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58
=> Fix golint import path

api/router.go
Requests will be logged in the following format:
```
Oct 30 22:56:41 dcos-e2e-39d6141e-c2f7-4c11-b599-d420d86b179b-master-0 dcos-diagnostics[14814]: 172.17.0.2 - - [30/Oct/2018:22:56:41 +0000] "GET /system/health/v1 HTTP/1.1" 200 4740
```
See: https://godoc.org/github.com/gorilla/handlers#LoggingHandler
Related: https://github.com/gorilla/mux/issues/416
=> Log requests with LoggingHandler

api/diagnostics.go, api/diagnostics_test.go, api/mock_tools_test.go
Currently to get status we query all nodes including local one.
This change try to get local status using local object.
=> Do NOT make remote call for local status

api/diagnostics.go, api/diagnostics_test.go
There is no reason to keep this indexes and nobody remember why it was introduced. Probably to prevent name conflict when running the same command twice (but why we would do this?).
This change jsut remove index. All logic and structures remains unchanged.
**Fixes:** [DCOS_OSS-4155](https://jira.mesosphere.com/browse/DCOS_OSS-4155)
**See:**
* https://github.com/dcos/dcos/pull/3446#discussion_r239251129
* https://github.com/dcos/dcos/pull/3212#issuecomment-418964030
=> Remove indexes from command names.

api/diagnostics_test.go, api/health_darwin.go, api/properties_darwin.go, cmd/listener_darwin.go, dcos/tools_darwin.go, units/helpers_darwin.go
This adds the necessary noop functions to allow compilation on Darwin, which makes it possible to run tests/linters/etc.
When possible I tried to copy the behaviour of the Windows-implementations and where not I opted to return an error to signal that it's an unsupported feature.
I'm still unsure about the comments, opinions welcome 😄
=> Fix compilation on Darwin by adding noop stubs of interfaces

api/diagnostics.go
> api/diagnostics.go:235::warning: declaration of "err" shadows declaration at api/diagnostics.go:206 (vetshadow)
Refs: https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-cluster-ops/job/dcos-diagnostics/job/dcos-diagnostics-pulls/296/console
=> Fix err shadows

api/diagnostics.go, api/diagnostics_test.go, api/providers.go, api/testdata/endpoint-config.json, fetcher/fetcher_test.go
Introduce `Optional` option in endpoint configuration for files. If a file is marked as optional then errors are swallowed and do not affect bundle creation process. Error is included as file content. This will allow us to gather files that are not always available on cluster such as rotated log files or configuration files for optional components.
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4949
=> Enable optional files in diagnsotics-bundle

Makefile, api/properties.go, api/properties_util.go, dcos/tools_darwin.go
By setting the envvar `NO_DOCKER` make will not run the given target
in a Docker container. This way builds are much faster because no
Docker image is built and no container has to be started.
On macOS `deadcode` complained about an unused function so that I had
to move that function into a file of its own and add build tags to it
so that it isn't compiled on macOS.
Also I removed some unused struct fields in macOS-specific code.
Fixes https://jira.mesosphere.com/browse/DCOS_OSS-5007
=> Add option to skip running builds in Docker

Makefile, api/diagnostics.go, api/diagnostics_test.go, api/providers.go, api/testdata/endpoint-config.json, fetcher/fetcher.go, fetcher/fetcher_test.go
Notable:
* API change for content returned by `/logs` of the diagnostics component. If this is an internal API to the diagnostics subsystem, and there are no other dependencies other than what's been changed in this PR, then we should be OK. Otherwise ... we'll need to consider an alternative approach here.
Related to https://jira.mesosphere.com/browse/DCOS-51618
=> Optional http endpoints

api/diagnostics_test.go, api/providers.go, api/testdata/endpoint-config-2.json, api/testdata/endpoint-config-3.json, api/testdata/endpoint-config.json, cmd/daemon.go, cmd/root_test.go, cmd/testdata/dcos-diagnostics-config-multiple-endpoints-configs.json, config/config.go
This change replaces `FlagDiagnosticsBundleEndpointsConfigFile string` with `FlagDiagnosticsBundleEndpointsConfigFiles []string` to allow configure multiple files.
Files will be merged and last added file will override previous one (order is important). This change allows us to have common configuration between OSS and EE and keep EE specific configuration in separated file.
Fixes: [DCOS-51484](https://jira.mesosphere.com/browse/DCOS-51484)
=> Read providers configuration from multiple files

api/diagnostics.go, api/diagnostics_test.go, api/handlers.go, api/providers.go, api/testdata/endpoint-config-2.json, api/testdata/endpoint-config.json, fetcher/fetcher.go, fetcher/fetcher_test.go
Currently if command does not exists we create empty file. This change includes `stderr` in command output file and if command does not exists or error (returns non `0` result) then mark it as failed and note it in `summarryErrorReport.txt`. This change introduce also `Optional` field for command so event if they fail, the bundle could be finished whiteout errors just like files.
Fixes: DCOS_OSS-5026
Refs: https://github.com/dcos/dcos-diagnostics/pull/94
=> Allow optional commands

Makefile, api/diagnostics.go
We need this gauge to be able to plot absolute bundle creation times
for each created bundle.
Also, I added the `docker` prerequisite to the `build` make target
because without this rule the Docker image for building the
dcos-diagnostics binary would not be built automatically.
refs https://jira.mesosphere.com/browse/DCOS_OSS-4962
=> Add bundle creation time gauge for Prometheus

api/diagnostics.go, api/handlers.go, cmd/root.go, cmd/root_test.go, units/helpers.go, units/helpers_darwin.go, units/helpers_linux.go, units/helpers_test.go, units/helpers_windows.go
This closes https://jira.mesosphere.com/browse/DCOS_OSS-5097
I added a TimeoutReadCloser to our units package that reads data from
an underlying ReadCloser only when the deadline of the given Context
has not been reached. Otherwise it stops reading and returns the error
retrieved from the Context (usually a DeadlineExceeded error).
When reading a systemd unit's log is interrupted we now log this fact
in the diagnostics output so that the consumer of the bundle knows
there's probably more in the journal than he sees.
=> Added timeout to systemd log reading; fixed `verbose` flag

api/diagnostics.go, api/diagnostics_test.go, cmd/daemon.go, fetcher/fetcher.go, fetcher/fetcher_test.go, mocks/prometheus.go
The histogram is now injected into Fetcher structs so we can also unit
test its calls properly.
refs https://jira.mesosphere.com/browse/DCOS_OSS-5136
=> Get rid of `fetchHistogram` global variable

api/router.go
Logging all request is not necessary when we have metrics. Requests logs are polluting logs and it's harder to find interesting information. The same data can be obtained with metrics.
Reverts: c139d7679716de8bff12f94895a1a1941b68d998
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5256
=> Remove requests logging

api/diagnostics.go, cmd/daemon.go, cmd/root.go, cmd/root_test.go, config/config.go
Admin router timeout is 60s our internal timeouts were 120s this leads to many [`504 Gateway Timeout`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) during bundle creation. This commit changes default timeouts to be less than 60s so we will have our internal timeout and do not need additional logic to handle 504 error.
Refs: https://stackoverflow.com/c/mesosphere/a/319/7
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5255
=> Decrease timeouts to be < than adminrouter timeout

api/rest/client.go, api/rest/client_test.go, api/router.go
https://jira.mesosphere.com/browse/DCOS_OSS-5329
Changes node bundle API to use `/system/health/v1/node/diagnostics` as its base path instead of `/system/health/v1/diagnostics`.
=> Change endpoint for node local bundles

api/rest/client.go, api/rest/client_test.go, api/rest/mock_client_test.go
This implements method wrappers for the list and delete endpoints of the node diagnostics API as well as updates the mock client to implement the modified interface.
https://jira.mesosphere.com/browse/DCOS_OSS-5348
=> Add list and delete functionality to Diagnostics Client

cmd/daemon.go, cmd/daemon_test.go, cmd/root.go, config/config.go
Add `--ip-discovery-command` config options that accepts path to `detect_ip` script.
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5384
=> Allow configuration of `detect_ip` script

api/rest/cluster_bundle_handler.go
In
https://github.com/dcos/dcos-diagnostics/blob/b5f70d473bc00b613729d940dfba98f7d1395182/api/rest/bundle_handler.go#L230
we use http.ServeFile that is handling lots of config specific seetings
for us. We should do the same for cluster handler.
=> Use http.ServeFile instead of creating it by hand

api/rest/bundle_handler.go, api/rest/cluster_bundle_handler.go
To make it easier to operate on diagnostics API with browser
add header that will tell how to handle content.
See:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
=> Add content type and content disposition headers to file response

api/rest/bundle_handler.go, api/rest/bundle_handler_test.go
BundleHandler.List should return after writing the error to the
response stream.
=> DCOS_OSS-5454 fix broken response body

api/rest/bundle_handler.go, api/rest/bundle_handler_test.go
* Add mutex to synchronize all writes to a file. The mutext is shared for all writes but since API need to support small amount of request it's fine.
* Do not update state file when get state detect file size differs from value stored in a file
* Sleep in E2E test to ensure everything is updated and we do not read previous version of a state file
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5331
=> Fix race on writing to bundle state file

api/rest/bundle_handler.go, api/rest/bundle_handler_test.go, api/rest/cluster_bundle_handler.go, api/rest/cluster_bundle_handler_test.go, cmd/daemon.go
Addresses https://jira.mesosphere.com/browse/DCOS_OSS-5454 by having `NewBundleHandler` and `NewClusterBundleHandler` initialize `workdir` if it doesn't exist.
=> Add workdir initialization to BundleHandler and ClusterBundleHandler

api/rest/bundle_handler.go, api/rest/bundle_handler_test.go, api/rest/cluster_bundle_handler.go, api/rest/cluster_bundle_handler_test.go, api/rest/type.go, api/rest/type_test.go
We stopped using Type after switching away from the old approach of using one API where the request specified what type of bundle to make so I repurposed it so that we can know if a bundle is a cluster bundle or a local bundle.
Addresses: https://jira.mesosphere.com/browse/DCOS_OSS-5456
=> Change `Type` to Local and Remote and make it part of Bundle metadata

api/rest/coordinator.go
When number of nodes is greater than number of workers application hangs. We have a deadlock because workers try to push result of their job to unbuffered channel that no gorutine is reading from.
To simulate this behavior change `numberOfWorkers` to 1 and see hanging tests.
https://github.com/dcos/dcos-diagnostics/blob/d9d8809a82ebb28755c0f5d7e1aa632f6c05ca6c/api/rest/coordinator.go#L19
Deleted comment duplicates:
https://github.com/dcos/dcos-diagnostics/blob/e92ee3ba8ace8e8cc4532bb4875736f0a19f2c11/api/rest/client.go#L47
=> Use Buffered channels

api/diagnostics.go, api/rest/bundle_handler.go, api/rest/bundle_handler_test.go, cmd/daemon.go, cmd/mesos_state.go, cmd/root_test.go, config/config.go
This PR creates dedicated context for each `Collect()` to limit time we spent on collection. 
Not all collectors supports context by default some of them use this wrapper https://github.com/dcos/dcos-diagnostics/blob/2457ed661d38f65fedede99ab0ec8e5b372cdc4f/io/readcloser.go#L9-L26
Context cancelation will result in error not on collector level but on data copy step https://github.com/dcos/dcos-diagnostics/blob/6048a18251e34b30ba61aef7edf2480b9f59e7f9/api/rest/bundle_handler.go#L232-L234
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5516
=> Limit how long single collector can work

api/rest/cluster_bundle_handler.go, api/rest/cluster_bundle_handler_test.go, docs/api.yaml
Add option to limit diagnostic bundle to masters or agents only. 
Replace apiary API documentation with OpenApi 
Fixes:
* https://jira.mesosphere.com/browse/DCOS_OSS-5472
* https://jira.mesosphere.com/browse/DCOS_OSS-5474
=> Allow limiting bundle to agents or masters only

api/rest/cluster_bundle_handler.go
Instead of pointers use `defaulOptions` to fill default values for
options.
See:
* https://stackoverflow.com/a/39161308/1387612
* https://github.com/dcos/dcos-diagnostics/pull/159#discussion_r331935835
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5472
=> Do not use pointers in options.

.travis.yml, Dockerfile, api/rest/bundle_handler.go, api/rest/bundle_handler_test.go, api/rest/client.go, cmd/daemon.go
* Reverted commit 1c0970b.
Creating local bundle takes much more than 5s. We don't need query node every 5s about its status. This change will reduce logs noise on larger cluster.
* Changed client log level from Info to Debug
Client should not log everything. It's logs are duplicated in coordinator. To reduce noise, let's keep only coordinator logs.
* Removed `summaryReport.txt` from bundle
summarryReport contains no meaningful information. All errors are stored in `report.json`. It was  reated to keep compatibility with an OLD API but that make no sens when we introduced report.json where we have a structure that we can extedn to provide more information about performed
actions.
https://github.com/dcos/dcos/pull/6032/commits/71f1ae60997731c7517532b16d7ca5b1af4c5536#diff-8fc8247f673fc5ccc1 …
=> Small improvements

api/diagnostics.go, api/diagnostics_test.go
When CocroachDB or Bouncer is down following response will be generated by old API
```yaml
{
"response_http_code":503,
"version":1,
"status":"could not get agent nodes: Get https://172.17.0.2:5050/slaves: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
}
```
The new API already returns meaningful information
```yaml
{
"code":500,
"error":"error getting agent nodes for bundle xyz: Get https://172.17.0.2:5050/slaves: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
}
```
Fixes: COPS-5439
Refs: https://github.com/dcos/dcos-core-cli/pull/384
=> Fail fast when can't get nodes

api/handlers_test.go, api/pull.go
Currently we make as many http calls as nodes we have.
This means we may create thousands connections to remote
agents. We should limit and control this number.
This PR introduces minimal change to add rate limiting
for that process. Number of concurrent connections will
be limited just to fit in pull interval window.
See: https://jira.d2iq.com/browse/COPS-5915
=> Limit number of concurrent status pulls

api/properties_windows.go, dcos/tools_windows.go
```
api\properties_windows.go:13: conversion from State (uint32) to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
=> Fix windows build

api/rest/bundle_handler_test.go
We have a flaky test due to timeout.
https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Fdcos-diagnostics-new/detail/PR-201/13/pipeline#step-14-log-506
=> Increase collector timeout in test

api/health_linux_test.go, api/health_windows.go, api/health_windows_test.go, api/properties_linux.go, api/properties_windows.go, dcos/interfaces.go
PR #47 introduced Healthy and Unhealthy status aliases.
Unfortunately it mismatched the constants.
This PR brings the proper names.
Refs: https://jira.d2iq.com/browse/COPS-6512
=> Fix (un)healthy mixed names
