- api/diagnostics.go
- api/handlers_test.go
- api/pull.go
- cmd/daemon.go
- scripts/test.sh
misspell is a lovely english language validator and corrector
https://github.com/client9/misspell
> add misspell check

- README.md
- add Apache 2.0 badge
- fix old velocity link with jenkins
- add Go Report Card badge
> update README.md with badges

- runner/runner.go
- runner/runner_test.go
https://jira.mesosphere.com/browse/DCOS_OSS-1345
> Output "cmd" instead of "full_cmd" in check list

- api/diagnostics.go
- util/string.go
- util/string_test.go
we want to have files in diagnostics bundle without any special character
other then "_", "-".
https://jira.mesosphere.com/browse/DCOS_OSS-671
> improve file names in diagnostics bundle

- runner/check.go
- runner/check_test.go
- runner/runner.go
- runner/runner_test.go
- vendor/github.com/dcos/dcos-go/exec/exec.go
- vendor/vendor.json
https://jira.mesosphere.com/browse/DCOS_OSS-1321
DC/OS PR: https://github.com/dcos/dcos/pull/1752
> Set environment for check commands

- api/diagnostics.go
currently a diagnostics bundle will always include a file
`errorsSummaryReport.txt`, even if no errors reported. With this change
the file will be added only if not empty.
> add errorsReport file to diagnostics bundle if not empty

- vendor/github.com/coreos/go-systemd/NOTICE
- vendor/github.com/coreos/go-systemd/dbus/dbus.go
- vendor/github.com/coreos/go-systemd/dbus/methods.go
- vendor/github.com/coreos/go-systemd/dbus/properties.go
- vendor/github.com/coreos/go-systemd/dbus/subscription.go
- vendor/github.com/godbus/dbus/MAINTAINERS
- vendor/github.com/godbus/dbus/README.markdown
- vendor/github.com/godbus/dbus/conn.go
- vendor/github.com/godbus/dbus/conn_darwin.go
- vendor/github.com/godbus/dbus/conn_other.go
- vendor/github.com/godbus/dbus/dbus.go
- vendor/github.com/godbus/dbus/default_handler.go
- vendor/github.com/godbus/dbus/doc.go
- vendor/github.com/godbus/dbus/encoder.go
- vendor/github.com/godbus/dbus/export.go
- vendor/github.com/godbus/dbus/message.go
- vendor/github.com/godbus/dbus/object.go
- vendor/github.com/godbus/dbus/server_interfaces.go
- vendor/github.com/godbus/dbus/sig.go
- vendor/github.com/godbus/dbus/transport_generic.go
- vendor/github.com/godbus/dbus/transport_unix.go
- vendor/github.com/godbus/dbus/transport_unixcred_freebsd.go
- vendor/github.com/godbus/dbus/variant.go
- vendor/vendor.json
- update `github.com/coreos/go-systemd`
- update `github.com/godbus/dbus`
https://jira.mesosphere.com/browse/COPS-2201
> bump vendor folder

- vendor/github.com/dcos/dcos-go/dcos/constants.go
- vendor/vendor.json
This PR is for picking up the default path updated in dcos-go for Windows powershell detect_ip.ps1 script change
> Update vendor.json for picking up dcos-go changes

- README.md
Hi there,
I thought I should add the information I got by asking to the place I anticipated it to be so that other clueless people like me may find the same info easier.
Feel free to reject if it's not helpful at all :)
> Add health mapping to readme

- .gometalinter.json
- Dockerfile
- api/diagnostics.go
- api/handlers.go
- api/helpers.go
- api/helpers_linux.go
- api/pull.go
- api/selftest.go
- cmd/daemon.go
- cmd/listener_linux.go
- cmd/listener_windows.go
- config/config.go
- scripts/test.sh
Fixed all issues reported by gometaliner or disabled failing checks or
change default thresholds.
Update Go from 1.9 to 1.10
https://github.com/alecthomas/gometalinter
> Introduce gometalinter instead hand crafted script

- .gometalinter.json
- api/diagnostics.go
- api/diagnostics_test.go
- scripts/test.sh
Change `time.Sleep` to busy waiting for bundle to complete.
> Do not sleep in tests

- .travis.yml
Coverage was done in job so after success trigger does not has coverage data.
> Fix codecov.io integration

- api/interfaces.go
- api/pull.go
Removed unused interface and move finder closer
to the place where its used.
> Remove unused code and move interface

- api/helpers_windows.go
- appveyor.yml
[![Build status](https://ci.appveyor.com/api/projects/status/tduckhj6gxyyyw46?svg=true)](https://ci.appveyor.com/project/janisz/dcos-diagnostics)
> Add appveyor.yml for Windows build

- CODEOWNERS
- owners.json
Codeowners will be automatically assigned for review.
See: https://blog.github.com/2017-07-06-introducing-code-owners/
> Add codeowners

- api/diagnostics.go
- api/diagnostics_test.go
- api/handlers_test.go
- api/helpers_linux.go
- api/helpers_test.go
- api/helpers_windows.go
- api/testdata/endpoint-config.json
Currenlty, the code has no tests. In this PR I added a bunch of tests for `DiagnosticsJob` and cleanup code a little bit.
> Add tests for DiagnosticsJob

- api/pull.go
- dcos/interfaces.go
Extracted common code to a function and use structured logs.
Log response body when status code is not 200.
Introduce `Unknown` value for `dcos.Health`
> Extract common code to a function in pull.go

- api/handlers.go
- api/router.go
* Create handlers structure that contains `Dt` object with all dependencies. This allows remove `Dt` from requests context and remove duplicated code.
* Changed some response code to 400 when a user provides incorrect data in a request.
* Rename unused request parameter `r` to `_` to make linter happy.
* Move helpers function to the bottom.
> Cleanup handlers code

- api/diagnostics.go
Currently we set some status fields after job was started.
This could lead to race – job was not running when API returned
it was started.
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4463
> Set job to running on start

- api/diagnostics.go
- api/diagnostics_test.go
Fixes: https://jira.mesosphere.com/browse/DCOS-45779
> Gather all errors in getStatusAll

- api/diagnostics.go
- api/pull.go
- dcos/finder.go
- dcos/finder_test.go
> Log response body on error

- api/diagnostics.go
- api/diagnostics_test.go
Currently, we are using a custom implementation of context. This change introduces [`standard context`](https://golang.org/pkg/context/) that is supported by HTTP client this it will fix problems with cancelling a running job.
> Use context instead of custom channel

- api/diagnostics.go
- api/diagnostics_test.go
- fetcher/fetcher.go
- fetcher/fetcher_test.go
Allow fetching data in parallel
> Create zip for each file

- Makefile
https://jira.mesosphere.com/browse/DCOS_OSS-4984
> Use vendor folder when installing

- Makefile
- api/health_linux_test.go
- api/health_windows_test.go
- cmd/root.go
- config/config.go
fixes https://jira.mesosphere.com/browse/DCOS_OSS-5008
> Standardize Makefile targets; add git revision to version

- api/diagnostics.go
- api/diagnostics_test.go
- api/handlers_test.go
- cmd/daemon.go
- cmd/root_test.go
- config/config.go
Fixes: [DCOS_OSS-4964](https://jira.mesosphere.com/browse/DCOS_OSS-4964)
> Make number of fetchers configurable

- cmd/daemon.go
- dcos/interfaces.go
refs https://jira.mesosphere.com/browse/DCOS_OSS-5136
> Get rid of the DefaultStateURL global variable

- cmd/daemon.go
- cmd/mesos_state.go
- cmd/mesos_state_test.go
- cmd/root.go
Fixes: https://jira.mesosphere.com/browse/DCOS-56380
> Add `mesos-state` command to CLI

- api/providers.go
- api/providers_test.go
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5428
> Do not flatten files in a bundle

- api/rest/bundle_handler.go
- api/rest/bundle_handler_test.go
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5467
> Store and error in optional file when it could not be collected.

- api/rest/client.go
- api/rest/coordinator.go
- api/rest/coordinator_test.go
- api/rest/mock_client_test.go
- api/rest/new_mock_client_test.go
- cmd/daemon_test.go
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5470
> Delete local bundles after fetching them

- api/rest/bundle_handler.go
- api/rest/bundle_handler_test.go
- api/rest/cluster_bundle_handler.go
- api/rest/cluster_bundle_handler_test.go
> Check if bundle is done before it could be fetch

- api/rest/bundle_handler.go
- api/rest/cluster_bundle_handler.go
- api/rest/cluster_bundle_handler_test.go
- api/rest/coordinator.go
> Mark bundle as failed when error occures

- api/rest/bundle_handler.go
- api/rest/bundle_handler_test.go
- api/rest/client.go
- api/rest/client_errors.go
- api/rest/client_test.go
- api/rest/cluster_bundle_handler.go
- api/rest/cluster_bundle_handler_test.go
- apiary.apib
Fixes: https://jira.mesosphere.com/browse/DCOS-58105
> Return 200 when deleting already deleted bundle

- api/diagnostics.go
- api/diagnostics_test.go
Old diagnostics bundle API does not stop increasing job duration
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5494
> Fix duration time

- CODEOWNERS
I've moved to other projects and will not be able to take on the responsibilities of a code owner, anymore. I'll be available for any questions, of course.
> Remove makkes from CODEOWNERS

- .travis.yml
- Dockerfile
- api/rest/client_test.go
- appveyor.yml
- cmd/mesos_state_test.go
- collector/collector_test.go
See: https://golang.org/doc/go1.14
> Bump Go version to 1.14
